# Generated by Django 4.1.3 on 2023-06-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_equip_stat1_profile_equip_stat2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_user',
        ),
    ]
