# Generated by Django 4.1.3 on 2023-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_user_profile_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lvl',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
