# Generated by Django 4.1.3 on 2023-07-22 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_armor_profile_critical_strike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trips',
            field=models.PositiveSmallIntegerField(default=32, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
