# Generated by Django 4.1.3 on 2023-07-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_textmessage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='profiles.profile'),
        ),
    ]
