# Generated by Django 4.1.3 on 2023-07-27 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_textmessage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
