# Generated by Django 4.1.3 on 2023-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_textmessage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
