# Generated by Django 4.1.3 on 2023-10-05 17:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_textmessage_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 300], upload_to='uploads/'),
        ),
    ]
