# Generated by Django 4.1.3 on 2023-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
