# Generated by Django 4.1.3 on 2023-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_training_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_points',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
