# Generated by Django 4.1.3 on 2023-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profile_training_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trip_cooldown',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
