# Generated by Django 4.1.3 on 2023-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_trip_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hp',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
