# Generated by Django 4.1.3 on 2023-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_combat1v1_result_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attacks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
