# Generated by Django 4.1.3 on 2023-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_rename_result1_combat1v1_result_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='text',
            field=models.TextField(max_length=1500),
        ),
    ]
