# Generated by Django 4.1.3 on 2023-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_alter_textmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='deleted_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='deleted_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='raport',
            field=models.BooleanField(default=False),
        ),
    ]
