# Generated by Django 4.1.3 on 2023-10-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_textmessage_deleted_1_textmessage_deleted_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='owner',
        ),
    ]
