# Generated by Django 4.1.3 on 2023-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_textmessage_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='saved',
            new_name='saved_1',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='saved_2',
            field=models.BooleanField(default=False),
        ),
    ]
