# Generated by Django 4.1.3 on 2023-10-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_rename_saved_textmessage_saved_1_textmessage_saved_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='saved_1',
            new_name='saved',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='saved_2',
        ),
    ]
