# Generated by Django 4.1.3 on 2023-10-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_rename_saved_1_textmessage_saved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='deleted_1',
            new_name='deleted_reciever',
        ),
        migrations.RenameField(
            model_name='textmessage',
            old_name='deleted_2',
            new_name='deleted_sender',
        ),
    ]
