# Generated by Django 4.1.3 on 2023-10-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_rename_deleted_1_textmessage_deleted_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='profiles.profile'),
        ),
    ]
