# Generated by Django 4.1.3 on 2023-10-28 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_alter_textmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='raport_kind',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
