# Generated by Django 4.1.3 on 2023-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_textmessage_raport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='raport_kind',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=20),
        ),
    ]
