# Generated by Django 4.1.3 on 2024-01-24 12:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_alter_profile_equip_dmg1_alter_profile_equip_dmg2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[400, 600], upload_to='uploads/'),
        ),
    ]
