# Generated by Django 4.1.3 on 2024-01-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranking_place',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
