# Generated by Django 5.1.3 on 2025-07-16 20:45

import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_profile_ranking_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[900, 900], upload_to='uploads/')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.TextField(default='', max_length=20)),
                ('lvl', models.PositiveSmallIntegerField(default=1)),
                ('stat1', models.PositiveIntegerField(default=0)),
                ('stat2', models.PositiveIntegerField(default=0)),
                ('stat3', models.PositiveIntegerField(default=0)),
                ('stat4', models.PositiveIntegerField(default=0)),
                ('stat5', models.PositiveIntegerField(default=0)),
                ('critical_strike', models.PositiveIntegerField(default=0)),
                ('critical_strike_dmg_mod', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('hp', models.PositiveIntegerField(default=100)),
                ('dmg1', models.PositiveIntegerField(default=1)),
                ('dmg2', models.PositiveIntegerField(default=1)),
                ('initiative', models.PositiveIntegerField(default=0)),
                ('attacks', models.PositiveIntegerField(default=0)),
                ('hit_mod', models.PositiveIntegerField(default=0)),
                ('special_attacks', models.ManyToManyField(blank=True, to='profiles.specialattack')),
            ],
        ),
    ]
