# Generated by Django 4.1.3 on 2023-06-25 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_profile_equip_stat1_profile_equip_stat2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_sufix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sufixes_number', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('item_type', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('sufix_pic', models.ImageField(blank=True, default='0.png', upload_to='sufix_pics')),
                ('name', models.TextField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'sufixes',
                'ordering': ['item_type', 'sufixes_number'],
                'unique_together': {('sufixes_number', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='item_prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_number', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('item_type', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('prefix_pic', models.ImageField(blank=True, default='0.png', upload_to='prefix_pics')),
                ('name', models.TextField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'prefixes',
                'ordering': ['item_type', 'prefix_number'],
                'unique_together': {('prefix_number', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='item_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_base_number', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('item_type', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('item_base_pic', models.ImageField(blank=True, default='0.png', upload_to='base_pics')),
                ('name', models.TextField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Item bases',
                'ordering': ['item_type', 'item_base_number'],
                'unique_together': {('item_base_number', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itemType', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_with_that_base', to='items.item_base')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items_list', to='profiles.profile')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_with_that_prefix', to='items.item_prefix')),
                ('sufix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_with_that_sufix', to='items.item_sufix')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
