# Generated by Django 4.1.3 on 2023-06-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_equip_stat1_profile_equip_stat2_and_more'),
        ('items', '0002_remove_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_list', to='profiles.profile'),
        ),
    ]
