# Generated by Django 4.1.3 on 2023-06-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_with_that_prefix', to='items.item_prefix'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sufix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_with_that_sufix', to='items.item_sufix'),
        ),
    ]
