# Generated by Django 4.1.3 on 2023-06-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_prefix_alter_item_sufix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_sufix',
            options={'ordering': ['item_type', 'sufix_number'], 'verbose_name_plural': 'sufixes'},
        ),
        migrations.RenameField(
            model_name='item_sufix',
            old_name='sufixes_number',
            new_name='sufix_number',
        ),
        migrations.AlterUniqueTogether(
            name='item_sufix',
            unique_together={('sufix_number', 'item_type')},
        ),
    ]
