# Generated by Django 4.1.3 on 2023-06-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_sufix',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='item_sufix',
            unique_together=set(),
        ),
    ]
