# Generated by Django 4.1.3 on 2023-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_sufix_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
    ]
