# Generated by Django 4.1.3 on 2024-01-04 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_trip_result_new_trip_result_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_base',
            name='type_of_wep',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
