# Generated by Django 4.1.3 on 2024-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_base_stat1_item_base_stat2_item_base_stat3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_prefix',
            options={'ordering': ['item_type', 'prefix_number'], 'verbose_name_plural': 'item prefixes'},
        ),
        migrations.AlterModelOptions(
            name='item_sufix',
            options={'ordering': ['item_type', 'sufix_number'], 'verbose_name_plural': 'item sufixes'},
        ),
        migrations.AddField(
            model_name='item_base',
            name='attacks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_prefix',
            name='attacks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_sufix',
            name='attacks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='item_sufix',
            unique_together={('sufix_number', 'item_type')},
        ),
    ]
