# Generated by Django 4.1.3 on 2024-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_item_prefix_options_alter_item_sufix_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_base',
            name='dmg1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_base',
            name='dmg2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_prefix',
            name='dmg1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_prefix',
            name='dmg2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_sufix',
            name='dmg1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_sufix',
            name='dmg2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
