# Generated by Django 4.1.3 on 2024-01-21 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_item_base_dmg1_alter_item_base_dmg2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_prefix',
            name='type_of_wep',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='item_sufix',
            name='type_of_wep',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
