# Generated by Django 4.1.3 on 2024-01-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_item_prefix_type_of_wep_item_sufix_type_of_wep'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item_base',
            unique_together={('item_base_number', 'item_type', 'type_of_wep')},
        ),
        migrations.AlterUniqueTogether(
            name='item_prefix',
            unique_together={('prefix_number', 'item_type', 'type_of_wep')},
        ),
        migrations.AlterUniqueTogether(
            name='item_sufix',
            unique_together={('sufix_number', 'item_type', 'type_of_wep')},
        ),
    ]
