# Generated by Django 4.1.3 on 2024-01-24 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_item_base_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_sufix',
            name='item_type',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
