# Generated by Django 5.1.3 on 2025-01-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_item_sufix_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_base',
            name='is_two_handed',
            field=models.BooleanField(default=False),
        ),
    ]
